### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by olalen** [And3rsL/VisonicAlarm-for-Hassio#3]
Tried the CrienClash code but could not get it to work in Hassio, saw your new updated ones. Which files do I need and in wich directories should they be placed. 
I get the following in Hassio;
2019-12-26 14:22:29 ERROR (MainThread) [homeassistant.components.hassio] Component error: visonicalarm - Integration 'visonicalarm' not found.

**Comment by a94marbo** [comment]
Download the 3 files from "custom_components/visonicalarm" and put them in the "custom_components" folder in config.
Put the code:

```
visonicalarm:
  host: host.alarmcompany.com
  user_code: 1234
  user_id: 00000000-0000-0000-0000-000000000000
  panel_id: 123456
  partition: ALL
```
in configuration.yaml

The host, user_code and panel_id are the same you are using when logging in to your system via the Visonic-GO app, and user_id is just a uniqe id generated from this site: https://www.uuidgenerator.net/ so make sure you replace 00000000-0000-0000-0000-000000000000 with an ID that you generate with that site. There is only support for the ALL partition.

Reboot the PI.
